databases:
  - name: library-db
    databaseName: library
    plan: free

services:
  - type: redis
    name: library-redis
    plan: free
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []

  - type: web
    name: library-api
    runtime: docker
    dockerContext: lab7
    dockerfilePath: lab7/Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: library-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: library-redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
